name: tcp_link
description: "Simplified TCP/IP Communication"
version: 1.0.0
repository: https://github.com/BenediktJSchlegel/tcp_link

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter: